// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTodo(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetTodo(ctx context.Context, id int32) (Todo, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListTodos(ctx context.Context, arg ListTodosParams) ([]Todo, error)
	ListTodosByUserID(ctx context.Context, arg ListTodosByUserIDParams) ([]Todo, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
